# Generated by Django 4.1.5 on 2023-04-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='phone',
            field=models.CharField(default='1234567891', max_length=20),
        ),
    ]
