# Generated by Django 4.1.3 on 2022-11-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('UID', models.CharField(max_length=100)),
                ('RCN', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShopKeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('shop_number', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('rice_purched', models.IntegerField()),
                ('rice_alloted', models.IntegerField()),
                ('dal_purched', models.IntegerField()),
                ('dal_alloted', models.IntegerField()),
                ('sugar_purched', models.IntegerField()),
                ('sugar_alloted', models.IntegerField()),
                ('wheat_purched', models.IntegerField()),
                ('wheat_alloted', models.IntegerField()),
            ],
        ),
    ]
