# Generated by Django 4.1.5 on 2023-04-08 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_clients_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('rice', models.CharField(max_length=100)),
                ('dal', models.CharField(max_length=100)),
                ('sugar', models.CharField(max_length=100)),
                ('wheat', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.clients')),
            ],
        ),
    ]
