# Generated by Django 4.2 on 2023-04-18 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobie_no', models.CharField(default='8446601001', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.clients')),
            ],
        ),
    ]
