# Generated by Django 4.2 on 2023-04-18 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='client',
        ),
    ]
